driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/school_project_manage?autoReconnect=true&connectTimeout=5000&socketTimeout=30000
username=root
password=041223Gan$
initialSize=50
maxActive=1000
minIdle=10
maxWait=60000
timeBetweenEvictionRunsMillis=30000
minEvictableIdleTimeMillis=60000
testOnBorrow=true
testWhileIdle=true
validationQuery=SELECT 1
validationQueryTimeout=5000
removeAbandoned=true
removeAbandonedTimeout=300
logAbandoned=true
druid.filters=stat,log4j
druid.connectionProperties=validationQuery="SELECT 1",validationQueryTimeout="5000",testOnBorrow="true",testWhileIdle="true"
#log4j.logger
